# Generated by Django 5.0.2 on 2024-08-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_livro_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="coautor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros_coautor",
                to="core.autor",
            ),
        ),
    ]
